### ISSUE TITLE
help called when no flags specified.

### ISSUE THREAD

**Issue by rnitta** [ksk001100/seahorse#26]
I made a  cli tool using this, and all flags should be optional, so implemented like: 

https://github.com/rnitta/commit_artist/blob/bbbbbbb73b6fd72a81a4188edc87e7bffd9f5135/src/main.rs#L14-L40
https://github.com/rnitta/commit_artist

and I got the problem.

<img width="386" alt="スクリーンショット 2020-02-24 9 57 46" src="https://user-images.githubusercontent.com/31783570/75123591-1f8fa680-56ec-11ea-93c7-f820c77791b5.png">
🤔

with a flag like `commit_artist -p 111111`, it will do.
It seems to be a bug for me.

**Comment by ksk001100** [comment]
Fix the bug today or tomorrow.

Thanks!!
