### ISSUE TITLE
Removing color module was a breaking change, should have bumped major version number

### ISSUE THREAD

**Issue by acshi** [ksk001100/seahorse#70]
Removing the color module caused some depending projects to fail to build.

For example, ruget uses the color module and now `cargo install ruget` fails, because cargo tries to use the newest compatible version of dependencies. A work-around would be to run `cargo install ruget --locked`, but the more friendly solution would be to yank current effected releases and re-release it with a major version bump to 2.0

**Comment by ksk001100** [comment]
@acshi 
v1.2.0 was yanked and v2.0.0 was released!
