### ISSUE TITLE
Allow actions to return Result<(),Error>?

### ISSUE THREAD

**Issue by timburks** [ksk001100/seahorse#75]
First, thanks for creating and sharing seahorse! I'm coming from a Go background where I've used [cobra](https://github.com/spf13/cobra) to build many CLIs and seahorse looks like it could fill a similar role for my Rust projects.

One thing that I like about Cobra and didn't find in seahorse is the ability to define actions that return error results. In Cobra we do this by setting the [`RunE`](https://github.com/spf13/cobra/blob/3d8ac432bdad89db04ab0890754b2444d7b4e1cf/command.go#L135) field in constructors. When actions return errors, the framework can automatically set the command exit value and print error messages and usage information, and instead of printing errors or panicking, action handlers return Go `Error` values.

I think an idiomatic Rust approach might be to define actions to return `Result<(),CommandError>` values, where `CommandError` is provided by seahorse. I'm experimenting with this in [this branch](https://github.com/timburks/seahorse/tree/action-result) which is much too rough to be a pull request because:

1. I haven't tried to update the tests for the change that I made.
2. I'm not sure that [this](https://github.com/timburks/seahorse/blob/162465fa6c534e552c161256c29083c490316454/src/action.rs#L23) is the right place to call `std::process::exit()`.
3. The change that I made is a breaking change! I just did it to see how it would look. I think a better approach would be to follow the Cobra example and have an alternate setter that sets an `ActionWithResult` (or whatever is appropriate to call this). That would make action handling more complex because only one of an `Action` and an `ActionWithResult` could be defined for a given command.

Feel free to disregard this for any reason, but if it seems worthwhile, I'm happy to work toward an appropriate PR that fixes the above problems and any other concerns.

**Comment by ksk001100** [comment]
@timburks 
Thanks for the suggestion.

2. I think it is good there.
3. As for breaking change, I think it would be better to implement ActionWithResult once and replace it with Action at the time of major upgrade in the future.

I think it is a good proposal and would appreciate it if you could make a PR.

**Comment by timburks** [comment]
As we've discussed in #76, it seems good to have a top-level function in `App` that returns `ActionResult` values instead of calling `panic1` for errors.

This allows client code to be written to [return a Result from main()](https://dev-notes.eu/2020/03/Return-a-Result-Type-from-the-Main-Function-in-Rust/):
```
use dotenv::dotenv;
use seahorse::{ActionResult, App};
use std::env;

mod mysubcommand;

fn main() -> ActionResult {
    dotenv().ok();
    let args: Vec<String> = env::args().collect();
    let name = &args[0].split("/").last().unwrap().to_string();
    let app = App::new(name)
        .description("Sample CLI")
        .usage(format!("{name} [command] [arg]"))
        .command(mysubcommand::command());
    return app.run_with_result(args);
}
```
